server {
    listen 80;
    charset     utf-8;

    # max upload size
    client_max_body_size 75M;   # adjust to taste

    # Send Orthanc requests requests to the Orthanc server.
    location ^~ / {
        proxy_set_header        Host $host:$server_port;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
        add_header              Access-Control-Allow-Origin *;

        proxy_pass              http://orthanc:8042/;
        proxy_read_timeout      90;
    }
}
