version: "2.1"
services:
  
  jupyter:
    image: code.oak-tree.tech:5005/courseware/oak-tree/dataops-examples/spark245-k8s-lm 
    volumes:
    - ./.local:/home/jovyan/
    - ./local:/home/jovyan/work/
    environment:
      OBJECTS_ENDPOINT: "http://object-storage:9000"
      OBJECTS_CONTAINER: playground 
      OBJECTS_SECRET: "jupyter@analytics"
      OBJECTS_ACCESSID: "jupyter"
    command: ["jupyter", "lab", "--ip", "0.0.0.0"]
    ports:
    - 8888:8888
    - 4040:4040