version: "2.1"
services:
  
  imaging:
    image: code.oak-tree.tech:5005/oak-tree/medical-imaging/imaging-development-env/sonador
    ports:
    - 8070:8070
    volumes:
    - ./config/sonador:/srv/www/sonador/config
    - ./data/sonador/docroot:/srv/www/sonador/docroot
    environment:
      SONADOR_SITECONFIG: "/srv/www/sonador/config/sonador.site.config"
      DJANGO_SETTINGS_MODULE: "sonador.settings"