FROM registry.oak-tree.tech/courseware/oak-tree/dataops-examples/spark-k8s-base

# Install kubectl
USER root
RUN apt install -y apt-transport-https apt-utils gnupg2 curl \
  && curl -LO https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl \
  && install -m 0755 kubectl /usr/local/bin/kubectl \
  && rm kubectl

# Switch back to Spark USER uid
USER 1000

