# Orthanc Deployment and In-Cluster Service
apiVersion: v1
kind: Service
metadata:
  name: orthanc
  namespace: imaging
spec:
  selector:
    app: orthanc
  ports:
  - protocol: TCP
    port: 8042
    targetPort: 8042
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orthanc
  labels:
    app: orthanc
  namespace: imaging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orthanc
  template:
    metadata:
      labels:
        app: orthanc-research
    spec:
      initContainers:
      - name: init-orthanc-db
        image: oaktreetech/orthanc-sonador
        command: ["/bin/bash"]
        args: ["-c", "cd /opt/orthanc/orthanc-sonador && alembic upgrade head"]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/orthanc/orthanc.json
          subPath: config
      containers:
      - name: orthanc
        image: oaktreetech/orthanc-sonador
        ports:
        - containerPort: 8042
        - containerPort: 4242
        volumeMounts:
        - name: config-volume
          mountPath: /etc/orthanc/orthanc.json
          subPath: config
        env:
        - name: POSTGRESQL_PLUGIN_ENABLED
          value: "true"
        - name: PYTHON_PLUGIN_ENABLED
          value: "true"
        - name: DICOM_WEB_PLUGIN_ENABLED
          value: "true"
        - name: AUTHORIZATION_PLUGIN_ENABLED
          value: "true"
        - name: AWS_S3_STORAGE_PLUGIN_ENABLED
          value: "false"
        - name: OHIF_PLUGIN_ENABLED
          value: "true"
        livenessProbe:
          exec:
            command:
            - /opt/orthanc/orthanc-sonador/maintenance/orthanc-server-status.py
          initialDelaySeconds: 30
          periodSeconds: 30
      volumes:
      - name: config-volume
        configMap:
          name: orthanc-config
