apiVersion: v1
kind: Service
metadata:
  name: sonador
  namespace: imaging
spec:
  selector:
    app: sonador
  ports:
  - protocol: TCP
    port: 8070
    targetPort: 8070
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonador
  labels:
    app: sonador
  namespace: imaging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonador
  template:
    metadata:
      labels:
        app: sonador
    spec:
      containers:
      - name: sonador
        image: code.oak-tree.tech:5005/oak-tree/medical-imaging/imaging-development-env/sonador
        ports:
        - containerPort: 8070
        volumeMounts:
        - name: config-volume
          mountPath: /srv/www/sonador/config/sonador.site.config
          subPath: config
        - name: sonador-migrations
          mountPath: /srv/www/sonador/config/dbmigrations
          subPath: dbmigrations
        env:
        - name: SONADOR_SITECONFIG
          value: /srv/www/sonador/config/sonador.site.config
        - name: DJANGO_SETTINGS_MODULE
          value: sonador.settings.production
      volumes:
      - name: config-volume
        configMap:
          name: sonador-config
      - name: sonador-migrations
        persistentVolumeClaim:
          claimName: sonador-migrations
