apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonador-migrations
  namespace: imaging
spec:
  storageClassName: glusterfs-simple
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
