FROM oaktreetech/sonador-airflow:3.1-python3.10
USER root


# Install Sonador 3D and PyVista for mesh processing
COPY requirements/ai.txt /opt/root/requirements/
RUN apt-get update \
    && apt-get install -y \
        build-essential gcc g++ libx11-6 libx11-dev libgl1 libxrender1 libxrender-dev xvfb \
    && pip3 install -r /opt/root/requirements/ai.txt --no-user

# Create virtual environment and install Total Segmentator. Amazon provider libraries
# are also installed so that AI segmentation tasks can use S3 comptaible object storage
# for temp files during processing. Sonador is also installed so it can be used for publishing
# artifacts after processing is complete.
USER airflow
RUN pip install airflow-ai-sdk[openai] --upgrade pip
RUN mkdir -p /home/airflow/env/requirements && cd /home/airflow/env \
    && python3 -m venv /home/airflow/env/totalsegmentator \
    && /home/airflow/env/totalsegmentator/bin/pip install --no-user --no-cache --upgrade pip
COPY requirements/totalsegmentator-dependencies.txt /home/airflow/env/requirements/
RUN /home/airflow/env/totalsegmentator/bin/pip install --no-user -r /home/airflow/env/requirements/totalsegmentator-dependencies.txt
RUN /home/airflow/env/totalsegmentator/bin/pip install --no-user totalsegmentator==2.12.0
RUN /home/airflow/env/totalsegmentator/bin/pip install --no-user \
    --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-3.1.5/constraints-3.10.txt" \
    "apache-airflow-providers-amazon[s3fs]==9.18.0"

# Copy helper scripts and modules to Total Segmentator env
COPY src/airflow-api.sonador_auth.py home/airflow/env/totalsegmentator/lib/python3.10/site-packages/sonador_auth.py
COPY src/airflow-api.sonador_hook.py home/airflow/env/totalsegmentator/lib/python3.10/site-packages/sonador_hook.py
COPY src/airflow-api.object_storage_hook.py home/airflow/env/totalsegmentator/lib/python3.10/site-packages/object_storage_hook.py
COPY src/airflow-totalsegmentator.execute.py home/airflow/env/totalsegmentator/airflow-totalsegmentator.execute.py
