from oaktreetech/sonador-airflow
USER root


# RUN sed -i 's|http://deb.debian.org/debian|http://archive.debian.org/debian|g' /etc/apt/sources.list \
#     && sed -i 's|http://security.debian.org/debian-security|http://archive.debian.org/debian-security|g' /etc/apt/sources.list \
#     && sed -i '/buster-updates/d' /etc/apt/sources.list \
#     && echo "Acquire::Check-Valid-Until false;" > /etc/apt/apt.conf.d/99no-check-valid-until \
#     && apt-get update


# Install Sonador 3D and PyVista for mesh processing
RUN apt-get update \
    && apt-get install -y \
        build-essential \
        gcc \
        g++ \
        libx11-6 \
        libx11-dev \
        libgl1 \
        libxrender1 \
        libxrender-dev \
    && pip3 install "sonador>=0.4.0b4" "sonador3d>=0.3.0a1" "pyvista>=0.44.2" "meshio" "pymeshfix" \
        --extra-index-url https://code.oak-tree.tech/api/v4/projects/335/packages/pypi/simple --no-user

# Create virtual environment and install Total Segmentator. Amazon provider libraries
# are also installed so that AI segmentation tasks can use S3 comptaible object storage
# for temp files during processing. Sonador is also installed so it can be used for publishing
# artifacts after processing is complete.
USER airflow
RUN pip install airflow-ai-sdk[openai] --upgrade pip
RUN mkdir $HOME/env && cd $HOME/env \
    && python3 -m venv $HOME/env/totalsegmentator \
    && $HOME/env/totalsegmentator/bin/pip install --no-user --upgrade pip \
    && $HOME/env/totalsegmentator/bin/pip install --no-user "sonador>=0.4.0b3" \
        "apache-airflow==3.1.5" "boto3==1.34.90" "psycopg2-binary==2.9.10" \
        --extra-index-url https://code.oak-tree.tech/api/v4/projects/335/packages/pypi/simple \
    && $HOME/env/totalsegmentator/bin/pip install --no-user totalsegmentator==2.5.0 torch==2.5.1

# Install Airflow providers for AWS in Total Segmentator env
RUN $HOME/env/totalsegmentator/bin/pip install --no-user "apache-airflow-providers-amazon[s3fs]==9.0.0"


# Copy helper scripts and modules to Total Segmentator env
COPY airflow-api.sonador_auth.py home/airflow/env/totalsegmentator/lib/python3.10/site-packages/sonador_auth.py
COPY airflow-api.sonador_hook.py home/airflow/env/totalsegmentator/lib/python3.10/site-packages/sonador_hook.py
COPY airflow-api.object_storage_hook.py home/airflow/env/totalsegmentator/lib/python3.10/site-packages/object_storage_hook.py
COPY airflow-totalsegmentator.execute.py home/airflow/env/totalsegmentator/airflow-totalsegmentator.execute.py
