version: "2.1"
services:
  
  jupyter:
    image: oaktreetech/root.itk:2022-0516 
    volumes:
    - ../local:/home/jovyan/work/
    - ../.local:/home/jovyan/
    environment:
      OBJECTS_ENDPOINT: "http://object-storage:9000"
      OBJECTS_CONTAINER: playground 
      OBJECTS_SECRET: "jupyter@analytics"
      OBJECTS_ACCESSID: "jupyter"
      JUPYTER_ALLOW_INSECURE_WRITES: "True"
    command: ["jupyter", "lab", "--ip", "0.0.0.0"]
    ports:
    - 8888:8888
    - 4040:4040
    
