version: "2.1"
services:

  object-storage:
    image: minio/minio
    volumes:
    - ../data/minio:/data
    environment:
      MINIO_ACCESS_KEY: "jupyter"
      MINIO_SECRET_KEY: "jupyter@analytics"
    command:
    - server
    - /data
    ports:
    - 9000:9000

  zookeeper:
    image: code.oak-tree.tech:5005/courseware/oak-tree/dataops-examples/zookeeper
    restart: always
    ports:
    - 2181:2181

  kafka:
    image: code.oak-tree.tech:5005/courseware/oak-tree/dataops-examples/kafka
    depends_on:
    - zookeeper
    restart: always
    ports:
    - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
