version: "2.1"
services:

  object-storage:
    image: minio/minio 
    volumes:
    - ../data/minio:/data
    environment:
      MINIO_ROOT_USER: "jupyter"
      MINIO_ROOT_PASSWORD: "jupyter@analytics"
    command: ["server", "--console-address", ":9001", "/data"]
    ports:
    - 9000:9000
    - 9001:9001

  zookeeper:
    image: registry.oak-tree.tech/courseware/oak-tree/dataops-examples/zookeeper
    restart: always
    ports:
    - 2181:2181

  kafka:
    image: registry.oak-tree.tech/courseware/oak-tree/dataops-examples/kafka
    depends_on:
    - zookeeper
    restart: always
    ports:
    - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
