version: "2.3"

services:
  
  jupyter:
    image: oaktreetech/root.3d:2026-01
    volumes:
    - ../local:/home/jovyan/work/
    - ../.local/.cache:/home/jovyan/.cache/
    - ../.local/.jupyter:/home/jovyan/.jupyter/
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    environment:
      OBJECTS_ENDPOINT: "http://object-storage:9000"
      OBJECTS_CONTAINER: playground 
      OBJECTS_SECRET: "jupyter@analytics"
      OBJECTS_ACCESSID: "jupyter"
      JUPYTER_ALLOW_INSECURE_WRITES: "True"
    entrypoint: ["/bin/bash", "-lc"]
    command: ["exec jupyter lab --ip=0.0.0.0 --no-browser"]
    shm_size: 8gb
    network_mode: host
