version: "3.8"

services:

  ollama-api:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
    - 11434:11434
    volumes:
    - ollama:/root/.ollama

    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    shm_size: 8gb    

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    depends_on:
    - ollama-api
    environment:
    - OLLAMA_BASE_URL=http://ollama-api:11434
    ports:
    - 8900:8080
    volumes:
    - open-webui:/app/backend/data

volumes:
  ollama:
  open-webui: