version: "2.1"
services:

  # Sonador PostgreSQL instance
  sonador-db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: images-control@medical-db
      POSTGRES_USER: postgres
      POSTGRES_DB: sonador
      PGDATA: /var/lib/postgresql/data/pgdata
  
  # Sonador Web Application
  imaging:
    image: oaktreetech/sonador:latest
    ports:
    - 8070:8070
    volumes:
    - ../config/sonador:/srv/www/sonador/config
    # - ../src/sonador:/srv/www/sonador/sonador
    environment:
      SONADOR_SITECONFIG: "/srv/www/sonador/config/sonador.site.config"
      DJANGO_SETTINGS_MODULE: "sonador.settings"
      SONADOR_SERVER_HOSTNAME: imaging.local
      SONADOR_SERVER_DESCRIPTION: "Sonador Development"
      SONADOR_USERNAME: dev01
      SONADOR_USER_FIRST_NAME: Development
      SONADOR_USER_LAST_NAME: User
      SONADOR_USER_EMAIL: "dev01@example.com"
      SONADOR_USER_PASSWORD: "sonador@development-env"
      SECURE_API_APITOKEN: "secure-api@sonador-dev"
    depends_on:
      sonador-db:
        condition: service_started
    command:
    - /bin/bash
    - -c
    - >
      sleep 20
      && cd /srv/www/sonador/sonador
      && python3 manage.py imaging-env-init
      && uvicorn sonador.asgi:application --port 8070 --host 0.0.0.0
