version: "2.1"
services:
  
  imaging:
    image: code.oak-tree.tech:5005/oak-tree/medical-imaging/imaging-development-env/sonador
    ports:
    - 8070:8070
    volumes:
    - ../config/sonador:/srv/www/sonador/config
    environment:
      SONADOR_SITECONFIG: "/srv/www/sonador/config/sonador.site.config"
      DJANGO_SETTINGS_MODULE: "sonador.settings"
      SONADOR_IMAGING_SERVER: dev01
      SONADOR_IMAGING_SERVER_INTERNAL_SCHEME: http
      SONADOR_IMAGING_SERVER_PORT: 8842
      SONADOR_IMAGING_SERVER_NAME: Orthanc-Dev
      SONADOR_IMAGING_SERVER_HOSTNAME: 127.0.0.1
      SONADOR_IMAGING_SERVER_SCHEME: http
      SONADOR_IMAGING_SERVER_DESCRIPTION: "Default Orthanc instance configured for the Oak-Tree Sonador reference environment."
    command:
    - /bin/bash
    - -c
    - >
      cd /srv/www/sonador/sonador
      && python3 manage.py imaging-env-init
      && apachectl -D FOREGROUND
